
include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    prefer_relative_imports: ignore
    invalid_assignment: warning
    missing_return: error
    dead_code: info

linter:
  rules:
    
    avoid_print: true
    prefer_single_quotes: true
    avoid_unused_constructor_parameters: true
    avoid_unnecessary_containers: true

    # Style Rules
    curly_braces_in_flow_control_structures: true
    avoid_redundant_argument_values: true
    prefer_const_constructors: true
    use_key_in_widget_constructors: true
