name: rota
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  firebase_database: ^11.1.6
  geolocator: ^13.0.2
  flutter_map: ^4.0.0
  latlong2: ^0.8.1
  geocoding: ^3.0.0
  http: ^0.13.6
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.1
  signature: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/logo2.png
# // add this line for setup
flutter_native_splash:
  color: "#DC2A34" # Background color of the splash screen
  image: assets/images/splash.png # Path to the splash screen image
  android: true
  ios: true
  web: false
